export const roles = {
  STAFF: "Staff",
  QA_COORDINATOR: "MARKETING COORDINATOR",
  QA_MANAGER: "MARKETING MANAGER",
  ADMIN: "Admin",
  ALL: ["Staff", "MARKETING COORDINATOR", "MARKETING MANAGER", "Admin"]
};
