export const roles = {
  STUDENT: "STUDENT",
  MARKETINGCOORDINATOR: "MARKETING COORDINATOR",
  MARKETINGMANAGER: "MARKETING MANAGER",
  ADMIN: "Admin",
  ALL: ["STUDENT", "MARKETING COORDINATOR", "MARKETING MANAGER", "Admin"]
};
